"""
Constants
"""

COMMAND_NAME = "we"
COMMAND_VAR = "_WORKENV_COMMAND"
COMPLETE_VAR = "_WORKENV_COMPLETE"
CONFIG_DEFAULT_FILENAME = "~/.workenv_config.yml"
CONFIG_ENV_VAR = "WORKENV_CONFIG_PATH"
PROJECT_DEFAULT_FILENAME = "workenv.yaml"
